### ISSUE TITLE
Direction of selection reversed in `coev_plot_delta_theta()`

### ISSUE THREAD

**Issue by erik-ringen** [ScottClaessens/coevolve#16]
The direction of selection (x -> y, y -> x) is reversed in the plots generated by the function `coev_plot_delta_theta()`. They are correct in the `summary()` output.

**Comment by ScottClaessens** [comment]
Thanks for spotting this. I'll take a look.

Currently, this function relies on the function `coev_get_delta_theta()` under the hood. But I prefer the generalisation to >2 variables offered by your `calculate_theta2()` function. I think we should find a way to fold this in instead.

**Comment by ScottClaessens** [comment]
This should be fixed in 32bc2f2. It was just a case of swapping the formula around in `facet_grid()`.

It would be great if you could test this again @erik-ringen. I tried testing the plot by fitting the model to data simulated with `coev_simulation_coevolution()`, but it takes quite a long time to fit the model on my laptop.

**Comment by ScottClaessens** [comment]
I have checked this with a model fitted to data from `coev_simulate_coevolution()`. The function seems to working as expected now. Closing this issue.
