### ISSUE TITLE
Choice of covariance kernels for distance GPs

### ISSUE THREAD

**Issue by ScottClaessens** [ScottClaessens/coevolve#43]
Gaussian Processes over spatial distances currently only use the exponential covariance kernel $\text{exp}(\rho \cdot D_{ij})$ where $D_{ij}$ is the scaled distance between taxa $i$ and $j$.

It would be useful to implement other possible kernels, including:

- [x] the exponentiated quadratic covariance kernel $\text{exp}(\rho \cdot D_{ij}^2)$

And possibly:

- [x] the Matern 3/2 kernel (see [here](https://mc-stan.org/docs/functions-reference/matrix_operations.html#matern-32-kernel))
- [ ] the Matern 5/2 kernel (see [here](https://mc-stan.org/docs/functions-reference/matrix_operations.html#matern-52-kernel))

**Comment by ErikRingen** [comment]
Agree it would be good to give people other options. One of the Matern kernels would be a nice default, as a compromise between the exponential kernel and the squared exponential, because the latter is infinitely smooth (infinitely differentiable) which probably is not realistic for most phenomena. Matern 5/2 is twice differentiable and has connections to penalized cubic splines (also twice diffentiable), which are the default spline in brms.

**Comment by ScottClaessens** [comment]
Implemented exponentiated-quadratic kernel in fe1371b.

**Comment by ScottClaessens** [comment]
Implemented Matern 3/2 kernel in d44633e.

**Comment by ScottClaessens** [comment]
I struggled to implement the Matern 5/2 kernel. It's more mathematically complex than the others. Stan does have internal functions for these covariance kernels, which probably code the kernels better than I can. But they take vectors rather than distance matrices so we can't use them here. When I tried my version, the authority model failed to fit.

I'm thinking that we can close this issue for now and come back to this kernel if necessary.
