### ISSUE TITLE
Why are autoregressive effects constrained to be negative?

### ISSUE THREAD

**Issue by ScottClaessens** [ScottClaessens/coevolve#68]
Question for @ErikRingen. This isn't really an issue, just something I've always wondered about the model.

Are these parameters constrained to be negative because the OU function is "pulling back" the variable to its own equilibrium value? If this parameter is _more_ negative, does that mean the autoregressive effect is stronger? Can we compare the strength of autoregressive effects between variables?

These are the kinds of questions that users will probably have too.

**Comment by ErikRingen** [comment]
Exactly, the autoregressive coefficients are constrained to be negative because this ensures they revert back to some equilibrium. As a heuristic you can reason about the off-diagonals like a discrete time VAR(1) by exponentiating the coefficients: when the autoregressive components approach 0, exp(0) = 1 which corresponds to a random walk (brownian motion). Yes you can compare the strength between variables, just keeping in mind that as with everything else the meaning depends on the scale. So comparing across variables will depend on pre-processing of variables and link functions. On this topic, I want to at some point implement the equivalent of `brms::posterior_epred()` for our functions, so that users can more easily reason about co-evolution on the original scale. Right now our functions are more like `brms::posterior_linpred()`.

**Comment by ScottClaessens** [comment]
Thanks for clearing that up. Makes sense! This will also be useful for when I present the model at the UCL workshop.

Regarding the `brms::posterior_epred()` point, I agree this would be useful, as the latent scale can be a bit abstract to think about. Maybe open a separate issue if you have more thoughts about this :)
